# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=250)),
                ('movie_name', models.CharField(blank=True, max_length=250)),
                ('typeofmovie', models.CharField(blank=True, max_length=250)),
                ('releaseyear', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
